#
# Module manifest for module 'AsciiText'
#
# Generated by: Michael Tartaggia
#
# Generated on: 2024-10-05
#
@{
    RootModule = 'AsciiText'
	ModuleVersion = '1.0.4'
	Description = 'Generates Ascii Text Art. Contains many different fonts. For examples run -> Get-Help Write-AsciiText -Examples'
	GUID = 'e727ded6-207a-4f91-b4e9-1d30e2514cba'
	Author = 'Michael Tartaggia'
	ProcessorArchitecture = 'None'
	FunctionsToExport = 'Show-Font', 'Get-AsciiText', 'Write-AsciiText', 'Get-Font'
	CmdletsToExport = '*' 
	VariablesToExport = '*'
	AliasesToExport = '*'
	FileList = @('AsciiText.psm1', 'AsciiText.psd1', 'Fonts\3DDiagonal.psf', 'Fonts\Arrows.psf', 'Fonts\ASCIINewRoman.psf', 'Fonts\Avatar.psf', 'Fonts\Big.psf', 'Fonts\Caligraphy.psf', 'Fonts\Chunky.psf', 'Fonts\Contessa.psf', 'Fonts\Digital.psf', 'Fonts\Doom.psf', 'Fonts\EftiFont.psf', 'Fonts\EftiRobot.psf', 'Fonts\Graceful.psf', 'Fonts\Graffiti.psf', 'Fonts\Impossible.psf', 'Fonts\LilDevil.psf', 'Fonts\Merlin1.psf', 'Fonts\Modular.psf', 'Fonts\Ogre.psf', 'Fonts\Pepper.psf', 'Fonts\Rectangles.psf', 'Fonts\SmallShadow.psf', 'Fonts\Stop.psf')


PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ASCII', 'Text', 'Art', 'Font','Write')


        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MrMichaelST/AsciiText'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Inital Release + bug fix + typos'



    }

}

}
