<#
.SYNOPSIS
    Generates a folder and file hierarchy from an ASCII/Unicode tree representation.

.DESCRIPTION
    New-FolderTree parses an ASCII or Unicode folder tree diagram (such as those
    generated by the 'tree' command, markdown bulleted lists, or found in README files)
    and automatically recreates the corresponding folder and file structure.

    It supports parsing Unicode box-drawing characters, standard ASCII tree
    connectors, and varying indentation styles. It also supports reading the
    tree hierarchy from a file, a string, the pipeline, or directly from the clipboard.

.PARAMETER TreeText
    The ASCII/Unicode tree hierarchy as a string or array of strings. Can be piped.

.PARAMETER Path
    The file path to a text file containing the tree hierarchy.

.PARAMETER FromClipboard
    If set, reads the tree hierarchy directly from the system clipboard.

.PARAMETER Destination
    The directory where the folder structure will be created. Defaults to the current directory.

.PARAMETER FoldersOnly
    If set, only directories will be created, and items identified as files will be skipped.

.PARAMETER AllAsFolders
    If set, treats all tree nodes as folders (even if they have file extensions like .txt, .js, etc.).

.EXAMPLE
    New-FolderTree -TreeText @'
    my-project
    ├── src
    │   ├── index.js
    │   └── utils.js
    ├── package.json
    └── README.md
    '@

.EXAMPLE
    Get-Clipboard | New-FolderTree -Destination C:\Projects\MyNewApp

.EXAMPLE
    New-FolderTree -Path .\project-structure.txt -FoldersOnly
#>
function New-FolderTree {
    [CmdletBinding(DefaultParameterSetName = 'Text', SupportsShouldProcess = $true)]
    param(
        [Parameter(Mandatory = $true, Position = 0, ParameterSetName = 'Text', ValueFromPipeline = $true)]
        [string[]]$TreeText,

        [Parameter(Mandatory = $true, ParameterSetName = 'Path')]
        [string]$Path,

        [Parameter(Mandatory = $true, ParameterSetName = 'Clipboard')]
        [switch]$FromClipboard,

        [Parameter(Mandatory = $false)]
        [string]$Destination = ".",

        [Parameter(Mandatory = $false)]
        [switch]$FoldersOnly,

        [Parameter(Mandatory = $false)]
        [switch]$AllAsFolders
    )

    begin {
        Write-Verbose "Initializing New-FolderTree..."

        # Resolve the destination directory path relative to the current PowerShell context
        $resolvedDestination = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Destination)
        Write-Verbose "Destination directory: '$resolvedDestination'"

        if (-not (Test-Path -Path $resolvedDestination)) {
            if ($PSCmdlet.ShouldProcess($resolvedDestination, "Create Destination Directory")) {
                $null = New-Item -ItemType Directory -Path $resolvedDestination -Force
                Write-Verbose "Created destination directory: '$resolvedDestination'"
            }
        }

        # Initialize history list to track active directories at each depth level.
        # We prepopulate it with a virtual root at depth -1.
        $history = [System.Collections.Generic.List[PSCustomObject]]::new()
        $history.Add([PSCustomObject]@{ Depth = -1; Path = $resolvedDestination })

        # List to collect all lines of the tree
        $allLines = [System.Collections.Generic.List[string]]::new()

        # If -Path is specified, read lines from the file
        if ($PSBoundParameters.ContainsKey('Path')) {
            $resolvedFilePath = Resolve-Path $Path -ErrorAction SilentlyContinue
            if (-not $resolvedFilePath) {
                Throw "The specified tree file path does not exist: '$Path'"
            }
            Write-Verbose "Reading tree hierarchy from file: '$($resolvedFilePath.Path)'"
            $fileLines = Get-Content -Path $resolvedFilePath.Path
            if ($fileLines) {
                $allLines.AddRange($fileLines)
            }
        }

        # If -FromClipboard is specified, read from clipboard
        if ($FromClipboard) {
            Write-Verbose "Reading tree hierarchy from clipboard..."
            try {
                $clipboardLines = Get-Clipboard
                if ($clipboardLines) {
                    $allLines.AddRange($clipboardLines)
                } else {
                    Write-Warning "Clipboard is empty or does not contain text content."
                }
            } catch {
                Throw "Failed to read from clipboard: $_"
            }
        }
    }

    process {
        # If TreeText is passed via pipeline or parameter, collect it
        if ($PSBoundParameters.ContainsKey('TreeText') -and $TreeText) {
            foreach ($text in $TreeText) {
                if ($text) {
                    # Split multi-line strings if any
                    $splitLines = $text -split '\r?\n'
                    foreach ($line in $splitLines) {
                        $allLines.Add($line)
                    }
                }
            }
        }
    }

    end {
        Write-Verbose "Loaded $($allLines.Count) lines to parse."

        # Script block to process a single line
        $processLine = {
            param([string]$line)

            # Skip completely empty or whitespace lines
            if ([string]::IsNullOrWhiteSpace($line)) { return }

            # Regex to match leading tree structure markers and whitespaces:
            # - [ │├└─┌┬┤┐┘┼|+\/\s\*] matches unicode/ascii tree symbols, slashes, whitespaces, asterisks
            # - -{2,} matches double or more hyphens (e.g. -- in +--)
            # - -(?=\s|[-+|\\/┌├└│─]) matches a single hyphen followed by a space or tree symbol (e.g. - in markdown lists)
            $prefixRegex = '^(?:[ │├└─┌┬┤┐┘┼|+\/\s\*]|-{2,}|-(?=\s|[-+|\\/┌├└│─]))*'
            $matched = [regex]::Match($line, $prefixRegex)
            $prefix = ""
            if ($matched.Success) {
                $prefix = $matched.Value
            }

            # Clean tab characters in prefix to normalize depth calculation (1 tab = 4 spaces)
            $cleanedPrefix = $prefix.Replace("`t", "    ")
            $depth = $cleanedPrefix.Length

            # Suffix is the remainder of the line, which represents the folder/file name
            $rawName = $line.Substring($prefix.Length).Trim()
            if ([string]::IsNullOrEmpty($rawName)) { return }

            # Check if original name had a trailing slash (indicating a directory)
            $endsWithSlash = $rawName.EndsWith('/') -or $rawName.EndsWith('\\')

            # Clean trailing slashes and spaces from the final name
            $name = $rawName.TrimEnd('\', '/')
            if ([string]::IsNullOrEmpty($name)) { return }

            # Determine if this item is a folder or file:
            $isFolder = $true
            if (-not $endsWithSlash -and -not $AllAsFolders) {
                # Heuristics to detect files:
                # 1. Contains a standard file extension of 1-5 alphanumeric characters (e.g., .txt, .json, .config)
                $hasExtension = $name -match '\.[a-zA-Z0-9]{1,5}$'
                # 2. Known common extensionless files
                $isKnownFile = $name -in @('LICENSE', 'Makefile', 'Dockerfile', 'Procfile', 'Gemini', 'gemini')

                if ($hasExtension -or $isKnownFile) {
                    $isFolder = $false
                }
            }

            # Find the appropriate parent folder from the history.
            # It must be the last/deepest folder in history with a depth strictly less than the current depth.
            $parent = $null
            for ($i = $history.Count - 1; $i -ge 0; $i--) {
                if ($history[$i].Depth -lt $depth) {
                    $parent = $history[$i]
                    break
                }
            }

            # Default to the virtual root if no parents are found (should theoretically not happen)
            if (-not $parent) {
                $parent = $history[0]
            }

            # Construct the full path of the item
            $newPath = Join-Path $parent.Path $name

            # Clean history of any directories at the same or deeper level
            for ($i = $history.Count - 1; $i -ge 0; $i--) {
                if ($history[$i].Depth -ge $depth) {
                    $history.RemoveAt($i)
                }
            }

            if ($isFolder) {
                Write-Verbose "Creating Directory: '$name' (Depth: $depth) inside '$($parent.Path)'"
                if ($PSCmdlet.ShouldProcess($newPath, "Create Directory")) {
                    $null = New-Item -ItemType Directory -Path $newPath -Force
                }
                # Record this folder in history so its children can reference it
                $history.Add([PSCustomObject]@{ Depth = $depth; Path = $newPath })
            } else {
                if ($FoldersOnly) {
                    Write-Verbose "Skipping File (FoldersOnly is set): '$name' (Depth: $depth)"
                    return
                }
                Write-Verbose "Creating File: '$name' (Depth: $depth) inside '$($parent.Path)'"
                if ($PSCmdlet.ShouldProcess($newPath, "Create File")) {
                    $null = New-Item -ItemType File -Path $newPath -Force
                }
                # Note: files are not added to history since they cannot contain children
            }
        }

        # Process all parsed lines
        foreach ($line in $allLines) {
            & $processLine $line
        }

        Write-Verbose "Folder tree creation process completed."
    }
}

<#
.SYNOPSIS
    Generates an ASCII or Unicode tree representation of a folder structure and copies it to the clipboard.

.DESCRIPTION
    Get-FolderTree recursively scans a directory and outputs its structure as a tree diagram.
    By default, it uses Unicode box-drawing characters and copies the tree text to the system clipboard.
    It automatically excludes common repository/meta folders (like .git and node_modules) unless overridden.

.PARAMETER Path
    The directory path to scan. Defaults to the current directory ('.').

.PARAMETER Depth
    The maximum depth to recursively traverse. Defaults to unlimited.

.PARAMETER Exclude
    An array of file/folder name patterns (wildcards supported) to exclude from the tree.

.PARAMETER ShowAll
    If set, overrides the default exclusion list and shows all files and folders (including .git, node_modules, etc.).

.PARAMETER FoldersOnly
    If set, only directories will be shown in the tree representation.

.PARAMETER UseASCII
    If set, uses plain ASCII characters (+--, |--, |) instead of Unicode box-drawing characters.

.PARAMETER NoClipboard
    If set, does not copy the resulting tree representation to the system clipboard.

.EXAMPLE
    Get-FolderTree

.EXAMPLE
    Get-FolderTree -Path .\src -Depth 2 -FoldersOnly

.EXAMPLE
    Get-FolderTree -Path C:\Projects\MyProject -UseASCII -Exclude "*.log", "temp*"
#>
function Get-FolderTree {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false, Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
        [string]$Path = ".",

        [Parameter(Mandatory = $false)]
        [int]$Depth = [int]::MaxValue,

        [Parameter(Mandatory = $false)]
        [string[]]$Exclude,

        [Parameter(Mandatory = $false)]
        [switch]$ShowAll,

        [Parameter(Mandatory = $false)]
        [switch]$FoldersOnly,

        [Parameter(Mandatory = $false)]
        [switch]$UseASCII,

        [Parameter(Mandatory = $false)]
        [switch]$NoClipboard
    )

    begin {
        Write-Verbose "Initializing Get-FolderTree..."
    }

    process {
        # Resolve target directory path
        $resolvedPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
        if (-not (Test-Path -Path $resolvedPath -PathType Container)) {
            Throw "The specified path does not exist or is not a folder: '$Path'"
        }

        $rootFolder = Get-Item -Path $resolvedPath
        Write-Verbose "Scanning folder: '$($rootFolder.FullName)'"

        # Determine connectors and prefixes
        if ($UseASCII) {
            $connectorNormal = "|-- "
            $connectorLast   = "+-- "
            $prefixNormal    = "|   "
            $prefixLast      = "    "
        } else {
            $connectorNormal = "├── "
            $connectorLast   = "└── "
            $prefixNormal    = "│   "
            $prefixLast      = "    "
        }

        # Build list of default excludes if -ShowAll is not set
        $excludePatterns = [System.Collections.Generic.List[string]]::new()
        if ($Exclude) {
            $excludePatterns.AddRange($Exclude)
        }
        if (-not $ShowAll) {
            $defaultExcludes = @('.git', 'node_modules', '.idea', '.vscode', 'bin', 'obj', 'dist', 'build', 'package-lock.json', '.gemini', '.VirtualBox', '.aish', '.aitk', '.bluefish', '.cache', '.cargo', '.chocolatey', '.codeium', '.codex', '.continue', '.copilot', '.crossnote', '.dbus-keyrings', '.ghcp-appmod', '.ghcp-appmod-java', '.idlerc', '.ipython', '.massCode', '.ollama', '.pencil', '.rest-client', '.rustup', '.skiko', '.ssh', 'AppData', 'borumi projects', 'fastcopy', 'loreforgedata', 'source')
            foreach ($item in $defaultExcludes) {
                if ($item -notIn $excludePatterns) {
                    $excludePatterns.Add($item)
                }
            }
        }

        # Helper function to check if an item matches exclude patterns
        $isExcluded = {
            param([System.IO.FileSystemInfo]$item)
            foreach ($pattern in $excludePatterns) {
                if ($item.Name -like $pattern) {
                    return $true
                }
            }
            return $false
        }

        # Output collection list
        # We start with the root folder name
        $treeOutput = [System.Collections.Generic.List[string]]::new()
        $treeOutput.Add($rootFolder.Name + "/")

        # Recursive helper script block
        $traverse = {
            param(
                [string]$currentPath,
                [string]$prefix,
                [int]$currentDepth
            )

            if ($currentDepth -ge $Depth) {
                return
            }

            if (-not (Test-Path -Path $currentPath)) { return }

            # Get immediate child items
            $rawChildren = Get-ChildItem -Path $currentPath
            
            # Filter children
            $filteredChildren = [System.Collections.Generic.List[System.IO.FileSystemInfo]]::new()
            foreach ($child in $rawChildren) {
                if ($FoldersOnly -and -not $child.PSIsContainer) {
                    continue
                }
                # Call the exclude helper scriptblock
                if (& $isExcluded $child) {
                    continue
                }
                $filteredChildren.Add($child)
            }

            # Sort children: directories first, then files (alphabetical)
            $sortedChildren = $filteredChildren | Sort-Object @{ Expression = { $_.PSIsContainer }; Descending = $true }, @{ Expression = { $_.Name }; Ascending = $true }

            $count = $sortedChildren.Count
            for ($i = 0; $i -lt $count; $i++) {
                $child = $sortedChildren[$i]
                $isLast = ($i -eq $count - 1)

                if ($isLast) {
                    $connector = $connectorLast
                } else {
                    $connector = $connectorNormal
                }
                
                $displayName = $child.Name
                if ($child.PSIsContainer) {
                    $displayName += "/"
                }

                $treeOutput.Add("$prefix$connector$displayName")

                if ($child.PSIsContainer) {
                    if ($isLast) {
                        $nextPrefix = $prefix + $prefixLast
                    } else {
                        $nextPrefix = $prefix + $prefixNormal
                    }
                    & $traverse $child.FullName $nextPrefix ($currentDepth + 1)
                }
            }
        }

        # Start traversal
        & $traverse $rootFolder.FullName "" 0

        # Combine output to string
        $treeString = $treeOutput -join [Environment]::NewLine

        # Output to console
        Write-Output $treeOutput

        # Copy to clipboard if requested
        if (-not $NoClipboard) {
            try {
                Set-Clipboard -Value $treeString
                Write-Verbose "ASCII tree successfully copied to the clipboard!"
            } catch {
                Write-Warning "Failed to copy tree to clipboard: $_"
            }
        }
    }
}

Export-ModuleMember -Function New-FolderTree, Get-FolderTree
